version: '3'

services:
  lab3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "3333"
    ports:
      - "3333:3333"
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 5454
      POSTGRES_DB: postgres